
# grayscale map style

border_fill_color = '#BBBBBB'
border_line_color = 'rgb(10%,10%,10%)'
border_line_width = 2.5

lake_fill_color = '#e6e6e6'

river_fill_color = '#e6e6e6'
river_line_width = 2

glacier_fill_color = '#ffffff'

[[elevation]]
height = 0
color = '#BBBBBB'

[[elevation]]
height = 2500
color = '#000000'
