
# grayscale map style

border_fill_color = '#BBBBBB'
border_line_color = 'rgb(30%,30%,30%)'
border_line_width = 1

lake_fill_color = '#eaeaea'

river_fill_color = '#eaeaea'
river_line_width = 2

glacier_fill_color = '#ffffff'

[[elevation]]
height = 0
color = '#BBBBBB'

[[elevation]]
height = 2500
color = '#000000'
